-- Generated from generator/demo_specs/aws-thailand-healthcare-hospital-capacity.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-healthcare-hospital-capacity
-- This is the schema that is actually deployed for THAILAND_HEALTHCARE_HOSPITAL_CAPACITY.

-- Alerts fire on the bottom tail of Bed Occupancy
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_BED_OCCUPANCY) AS T
  FROM RAW.BED_CENSUS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_BED_OCCUPANCY <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_BED_OCCUPANCY), 2) AS AVG_BED_OCCUPANCY,
  ROUND(AVG(f.KPI_ICU_AVAILABILITY), 2) AS AVG_ICU_AVAILABILITY,
  ROUND(AVG(f.KPI_AVG_LENGTH_OF_STAY), 2) AS AVG_LENGTH_OF_STAY,
  ROUND(AVG(f.KPI_PREDICTED_SURGE_7D), 2) AS AVG_PREDICTED_SURGE_7D,
  ROUND(AVG(f.KPI_ER_WAIT_AVG), 2) AS AVG_ER_WAIT
FROM RAW.BED_CENSUS f
JOIN RAW.THAI_PRIVATE_HEALTH e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_BED_OCCUPANCY), 2) AS AVG_BED_OCCUPANCY,
  ROUND(AVG(f.KPI_ICU_AVAILABILITY), 2) AS AVG_ICU_AVAILABILITY,
  ROUND(AVG(f.KPI_AVG_LENGTH_OF_STAY), 2) AS AVG_LENGTH_OF_STAY,
  ROUND(AVG(f.KPI_PREDICTED_SURGE_7D), 2) AS AVG_PREDICTED_SURGE_7D,
  ROUND(AVG(f.KPI_ER_WAIT_AVG), 2) AS AVG_ER_WAIT
FROM RAW.BED_CENSUS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_BED_OCCUPANCY) AS KPI_BED_OCCUPANCY, AVG(KPI_ICU_AVAILABILITY) AS KPI_ICU_AVAILABILITY, AVG(KPI_AVG_LENGTH_OF_STAY) AS KPI_AVG_LENGTH_OF_STAY, AVG(KPI_PREDICTED_SURGE_7D) AS KPI_PREDICTED_SURGE_7D, AVG(KPI_ER_WAIT_AVG) AS KPI_ER_WAIT_AVG FROM RAW.BED_CENSUS),
     en AS (SELECT SUM(KPI_FACILITIES_MONITORED) AS KPI_FACILITIES_MONITORED, SUM(KPI_SURGERY_QUEUE) AS KPI_SURGERY_QUEUE FROM RAW.THAI_PRIVATE_HEALTH)
  SELECT 1 AS SORT_ORDER, 'Bed Occupancy' AS TITLE, KPI_BED_OCCUPANCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BED_OCCUPANCY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'ICU Availability' AS TITLE, KPI_ICU_AVAILABILITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ICU_AVAILABILITY)) AS DECIMAL(38,0))) || ' ' || 'beds' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Length of Stay' AS TITLE, KPI_AVG_LENGTH_OF_STAY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_LENGTH_OF_STAY), 1) AS DECIMAL(38,1))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Facilities Monitored' AS TITLE, KPI_FACILITIES_MONITORED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FACILITIES_MONITORED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Predicted Surge (7d)' AS TITLE, KPI_PREDICTED_SURGE_7D AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_PREDICTED_SURGE_7D)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Surgery Queue' AS TITLE, KPI_SURGERY_QUEUE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SURGERY_QUEUE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'ER Wait (Avg)' AS TITLE, KPI_ER_WAIT_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ER_WAIT_AVG)) AS DECIMAL(38,0))) || ' ' || 'min' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
