-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Hospital Capacity & Revenue Optimization
-- ============================================================================
USE DATABASE HOSPITAL_CAPACITY;
USE SCHEMA ML;

-- ML.FORECAST: ADMISSION_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.ADMISSION_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.ADMISSION_TIMESERIES'),
  SERIES_COLNAME => 'HOSPITAL_DEPT',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.ADMISSION_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.ADMISSION_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: CENSUS_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CENSUS_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.REALTIME_BED_STATUS'),
  SERIES_COLNAME => 'HOSPITAL_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CENSUS_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CENSUS_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.REALTIME_BED_STATUS'), SERIES_COLNAME => 'HOSPITAL_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

