-- ============================================================================
-- 99_RESET.SQL — Reset Hospital Capacity & Revenue Optimization to clean demo state
-- ============================================================================
USE DATABASE HOSPITAL_CAPACITY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_CENSUS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_PLANS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.REALTIME_BED_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.ADMISSION_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.REVENUE_PER_BED_DAY REFRESH;
ALTER DYNAMIC TABLE CURATED.OR_UTILIZATION REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM HOSPITAL_CAPACITY.RAW.BED_CENSUS → 500000
-- SELECT COUNT(*) FROM HOSPITAL_CAPACITY.RAW.ADMISSIONS → 180000
-- SELECT COUNT(*) FROM HOSPITAL_CAPACITY.CURATED.REALTIME_BED_STATUS WHERE UTILIZATION > 0.90 → 3

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_PLANS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_CENSUS RESUME;
